In [2]:
# Dependencies

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os

import time
import math
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.utils.data import DataLoader

from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence

import preprocess

In [3]:
# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [4]:
# Recurrent neural network (many-to-one)
class RNN(nn.Module):
    def __init__(self):
        super(RNN, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, 2)
        self.linear = nn.Linear(hidden_size, num_classes)

    def forward(self, input_seq):
        output_seq, _ = self.lstm(input_seq)
        last_output = output_seq[-1]
        class_predictions = self.linear(last_output)
        return class_predictions

In [5]:
## Normal sEMG dataset
file_path = "./SEMG_DB1/N_TXT/"

input_array, output_array = preprocess.preprocess(file_path)
input_array = input_array.transpose(1,0,2)
print(input_array.shape)
print(input_array)

input_tensor= torch.from_numpy(input_array).float()

print(input_tensor.shape)

/Users/hobinkang/Desktop/EMG_Leg_Classification/preprocess.py:27: ConversionWarning: Some errors were detected !
    Line #7308 (got 1 columns instead of 5)
    Line #7309 (got 1 columns instead of 5)
    Line #7310 (got 1 columns instead of 5)
    Line #7311 (got 1 columns instead of 5)
    Line #7312 (got 1 columns instead of 5)
    Line #7313 (got 1 columns instead of 5)
    Line #7314 (got 1 columns instead of 5)
    Line #7315 (got 1 columns instead of 5)
    Line #7316 (got 1 columns instead of 5)
    Line #7317 (got 1 columns instead of 5)
    Line #7318 (got 1 columns instead of 5)
    Line #7319 (got 1 columns instead of 5)
    Line #7320 (got 1 columns instead of 5)
    Line #7321 (got 1 columns instead of 5)
    Line #7322 (got 1 columns instead of 5)
    Line #7323 (got 1 columns instead of 5)
    Line #7324 (got 1 columns instead of 5)
    Line #7325 (got 1 columns instead of 5)
    Line #7326 (got 1 columns instead of 5)
    Line #7327 (got 1 columns instead of 5)
  self.

(36900, 33, 5)
[[[-8.00e-04 -4.60e-03  3.00e-03 -9.80e-03 -5.91e+01]
  [-3.00e-03 -3.00e-03 -1.95e-02  4.50e-03 -5.26e+01]
  [-3.00e-03  7.00e-04 -8.00e-04  6.70e-03 -6.00e-01]
  ...
  [-8.00e-04  1.50e-03  7.00e-04 -2.30e-03  4.90e+00]
  [-1.50e-03  0.00e+00  7.00e-04  0.00e+00 -1.00e+00]
  [ 4.50e-03  2.20e-03  7.00e-04  3.70e-03  2.60e+00]]

 [[ 7.00e-04 -5.30e-03  1.50e-03 -6.00e-03 -5.92e+01]
  [-8.00e-04 -1.50e-03 -2.03e-02  5.20e-03 -5.26e+01]
  [-1.50e-03  3.30e-02  7.00e-04  1.27e-02 -6.00e-01]
  ...
  [-8.00e-04 -8.00e-04  3.00e-03 -2.30e-03  4.90e+00]
  [-8.00e-04  1.50e-03  3.00e-03 -1.50e-03 -1.00e+00]
  [ 1.42e-02 -6.00e-03  7.00e-04  0.00e+00  2.60e+00]]

 [[ 0.00e+00 -4.60e-03  3.00e-03 -1.50e-03 -5.93e+01]
  [-1.50e-03 -1.50e-03 -1.65e-02  3.70e-03 -5.26e+01]
  [-8.00e-04  2.92e-02  0.00e+00  5.20e-03 -6.00e-01]
  ...
  [ 0.00e+00  7.00e-04  1.50e-03  0.00e+00  4.90e+00]
  [ 7.00e-04  1.50e-03  3.70e-03 -2.30e-03 -1.00e+00]
  [ 1.65e-02 -6.00e-03  0.00e+00  0.00e+00  2

/Users/hobinkang/Desktop/EMG_Leg_Classification/preprocess.py:27: ConversionWarning: Some errors were detected !
    Line #6930 (got 1 columns instead of 5)
    Line #6931 (got 1 columns instead of 5)
    Line #6932 (got 1 columns instead of 5)
    Line #6933 (got 1 columns instead of 5)
    Line #6934 (got 1 columns instead of 5)
    Line #6935 (got 1 columns instead of 5)
    Line #6936 (got 1 columns instead of 5)
    Line #6937 (got 1 columns instead of 5)
    Line #6938 (got 1 columns instead of 5)
    Line #6939 (got 1 columns instead of 5)
    Line #6940 (got 1 columns instead of 5)
    Line #6941 (got 1 columns instead of 5)
    Line #6942 (got 1 columns instead of 5)
    Line #6943 (got 1 columns instead of 5)
    Line #6944 (got 1 columns instead of 5)
    Line #6945 (got 1 columns instead of 5)
    Line #6946 (got 1 columns instead of 5)
    Line #6947 (got 1 columns instead of 5)
  self.array = np.genfromtxt(self.path, skip_header=7, invalid_raise=False)
/Users/hobinkang/De

In [6]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

## One Hot Encode Prediction

print(output_array)
# convert output_array to one hot encoded classes
values = array(output_array)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

output_tensor= torch.from_numpy(integer_encoded)
print(output_tensor)

['mar', 'sen', 'pie', 'sen', 'pie', 'mar', 'pie', 'sen', 'pie', 'mar', 'pie', 'pie', 'pie', 'mar', 'sen', 'mar', 'pie', 'mar', 'sen', 'pie', 'sen', 'mar', 'sen', 'mar', 'pie', 'mar', 'sen', 'sen', 'sen', 'sen', 'mar', 'mar', 'pie']
['mar' 'sen' 'pie' 'sen' 'pie' 'mar' 'pie' 'sen' 'pie' 'mar' 'pie' 'pie'
 'pie' 'mar' 'sen' 'mar' 'pie' 'mar' 'sen' 'pie' 'sen' 'mar' 'sen' 'mar'
 'pie' 'mar' 'sen' 'sen' 'sen' 'sen' 'mar' 'mar' 'pie']
[0 2 1 2 1 0 1 2 1 0 1 1 1 0 2 0 1 0 2 1 2 0 2 0 1 0 2 2 2 2 0 0 1]
tensor([0, 2, 1, 2, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0, 2, 0, 1, 0, 2, 1, 2, 0, 2, 0,
        1, 0, 2, 2, 2, 2, 0, 0, 1])


In [7]:
time_steps = input_tensor.shape[0]
print(time_steps)
batch_size = input_tensor.shape[1]
print(batch_size)
input_size = input_tensor.shape[2]
print(input_size)
num_classes = 3
hidden_size = 128 
num_layers = 2
num_epochs = 2
learning_rate = 0.01

36900
33
5


In [8]:
input_tensor[:,1,:][:,None,:].shape

torch.Size([36900, 1, 5])

In [9]:
model = RNN().to(device)

In [10]:
# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
# Train the model
total_step = len(input_tensor)
for epoch in range(num_epochs):
    for i in range(0,input_tensor.shape[1]):
        
        # Forward pass
        outputs = model(input_tensor[:,i,:][:,None,:].to(device))
        print(outputs)
        
        loss = criterion(outputs, torch.LongTensor([output_tensor[i]]).to(device))
        print(loss)
        
        # Backward and optimize
        optimizer.zero_grad()
        print("1")
        loss.backward()
        print("2")
        optimizer.step()
        print("3")
        
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

tensor([[0.0002, 0.0627, 0.0161]], grad_fn=<ThAddmmBackward>)
tensor(1.1251, grad_fn=<NllLossBackward>)
1
